package gestioncv;

import java.awt.event.ActionEvent;
import java.sql.*;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Home extends javax.swing.JFrame {

    static Connection conn;
    static ResultSet rs;
    static PreparedStatement pst;
    String first;
    String last;
    int id;
    
    public Home(){
        super("Welcome to your CVFix space!");
        initComponents();
        
        //ADD ACTION GROUP
        jButton2.setAction(abstractActionAdd);
        jMenuItem2.setAction(abstractActionAdd);
        
        //DELETE ACTION GROUP
        jButton3.setAction(abstractActionDelete);
        jMenuItem3.setAction(abstractActionDelete);
        
        //MODIFY ACTION GROUP
        jButton4.setAction(abstractActionModify);
        jMenuItem4.setAction(abstractActionModify);
        
        //CONSULT ACTION GROUP
        jButton1.setAction(abstractActionConsult);
        jMenuItem5.setAction(abstractActionConsult);
    }
    
    public Home(String mail, String pwd) {
        super("Welcome to your CVFix space!");
        initComponents(); 
        conn=connexion.ConnectDb();
        
        //ADD ACTION GROUP
        jButton2.setAction(abstractActionAdd);
        jMenuItem2.setAction(abstractActionAdd);
        
        //DELETE ACTION GROUP
        jButton3.setAction(abstractActionDelete);
        jMenuItem3.setAction(abstractActionDelete);
        
        //MODIFY ACTION GROUP
        jButton4.setAction(abstractActionModify);
        jMenuItem4.setAction(abstractActionModify);
        
        //CONSULT ACTION GROUP
        jButton1.setAction(abstractActionConsult);
        jMenuItem5.setAction(abstractActionConsult);
        
        //RECOGNIZING THE USER
        String sql ="select userID, firstName, lastName from user where email=? and password=?" ; 
        
        try{
             pst=conn.prepareStatement(sql);
             String e = mail;
             pst.setString(1,e);
             String p = pwd;
             pst.setString(2,p);
             rs=pst.executeQuery();
             
            if(rs.next()){
            id= rs.getInt("userID");
            first = rs.getString("firstName");
            last= rs.getString("lastName");
            rs.close();
            pst.close();
            //System.out.println("welcome home!");
            jMenu1.setText(first+" "+last);
       
            }
        
            }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
                         }finally {
            try{
            rs.close();
            pst.close();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
                         }
            
    }
        
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CV2.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 400));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(36, 177, 224));
        jTextPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextPane1.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("           LET'S GET STARTED!\n   Choose an action to proceed:");
        jTextPane1.setToolTipText("");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 80));

        jButton1.setBackground(jTextPane1.getBackground());
        jButton1.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consult CV.png"))); // NOI18N
        jButton1.setText("Consult all CV's");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 240, 50));

        jButton2.setBackground(jTextPane1.getBackground());
        jButton2.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add CV.png"))); // NOI18N
        jButton2.setText("Create a new CV");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 240, 50));

        jButton3.setBackground(jTextPane1.getBackground());
        jButton3.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete CV.png"))); // NOI18N
        jButton3.setText("Delete an existing CV");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 240, 50));

        jButton4.setBackground(jTextPane1.getBackground());
        jButton4.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify CV.png"))); // NOI18N
        jButton4.setText("Modify an existing CV");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 240, 50));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CV.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 230, -1));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));

        jMenu1.setText("Username");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logout.png"))); // NOI18N
        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add CV.png"))); // NOI18N
        jMenuItem2.setText("Add CV");
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete CV.png"))); // NOI18N
        jMenuItem3.setText("Delete CV");
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify CV.png"))); // NOI18N
        jMenuItem4.setText("Modify CV");
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consult CV.png"))); // NOI18N
        jMenuItem5.setText("Consult CV's");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      setVisible(false);
      System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //ADD CV ACTION
    ImageIcon img = new ImageIcon("C:\\Users\\Hayouba\\Desktop\\H!BA\\Projet Java\\Images\\add CV.png");
    AbstractAction abstractActionAdd = new AbstractAction("Create a new CV", img) { 
         
            @Override
            public void actionPerformed(ActionEvent args) { 
                setVisible(false);
                AddCV cv=new AddCV(first,id); 
                //Home.setUpLoading();
                cv.setVisible(true);
            } 
        };
    
    //DELETE CV ACTION
    ImageIcon img1 = new ImageIcon("C:\\Users\\Hayouba\\Desktop\\H!BA\\Projet Java\\Images\\delete CV.png");
    AbstractAction abstractActionDelete = new AbstractAction("Delete an existing CV", img1) { 
         
            @Override
            public void actionPerformed(ActionEvent args) { 
                setVisible(false);
               
            } 
        };
    
     //MODIFY CV ACTION
    ImageIcon img2 = new ImageIcon("C:\\Users\\Hayouba\\Desktop\\H!BA\\Projet Java\\Images\\modify CV.png");
    AbstractAction abstractActionModify = new AbstractAction("Modify an existing CV", img2) { 
         
            @Override
            public void actionPerformed(ActionEvent args) { 
                setVisible(false);
               
            } 
        };
    
    //CONSULT CV ACTION
    ImageIcon img3 = new ImageIcon("C:\\Users\\Hayouba\\Desktop\\H!BA\\Projet Java\\Images\\consult CV.png");
    AbstractAction abstractActionConsult = new AbstractAction("Consult all your CV's", img3) { 
         
            @Override
            public void actionPerformed(ActionEvent args) { 
                setVisible(false);
               
            } 
        };
    
    //TEST HERE
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    
 
}
