package gestioncv;

import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Signup extends javax.swing.JFrame {
   
     static Connection conn;
     static ResultSet rs;
     static PreparedStatement pst;
    public Signup() {
        super("Sign Up");
        initComponents();
        conn=connexion.ConnectDb();
        
        //ADD ICON TO THE BUTTON
   /*   try {
        Image img = ImageIO.read(getClass().getResource("sign-in.png"));
        jButton1.setIcon(new ImageIcon(img));
        } catch (Exception ex) {
        System.out.println(ex);
       }   */
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 270));

        jLabel2.setBackground(new java.awt.Color(36, 177, 224));
        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGN UP NOW!");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 210, 50));

        getContentPane().add(jPanel2);

        jPanel1.setBackground(jLabel2.getBackground());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Last Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 30));

        jTextField2.setBackground(jPanel1.getBackground());
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("Insert your last name...");
        jTextField2.setToolTipText("Insert last name");
        jTextField2.setBorder(null);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, -1));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, 10));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("First Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 30));

        jTextField1.setBackground(jPanel1.getBackground());
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("Insert your first name...");
        jTextField1.setToolTipText("Insert first name");
        jTextField1.setBorder(null);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, -1));

        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 270, 10));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("E-mail:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, 30));

        jTextField3.setBackground(jPanel1.getBackground());
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setText("Insert your e-mail...");
        jTextField3.setToolTipText("Insert e-mail");
        jTextField3.setBorder(null);
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, -1));

        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 270, 10));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 30));

        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 270, 10));

        jPasswordField1.setBackground(jPanel1.getBackground());
        jPasswordField1.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setToolTipText("Insert password");
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Confirm Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, 30));

        jPasswordField2.setBackground(jPanel1.getBackground());
        jPasswordField2.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField2.setToolTipText("Confirm password");
        jPasswordField2.setBorder(null);
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, -1));

        jSeparator5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jSeparator5.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 270, 10));

        jButton1.setBackground(jPanel2.getBackground());
        jButton1.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-in.png"))); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.setToolTipText("Sign up!");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 270, 50));

        jCheckBox2.setBackground(jPanel1.getBackground());
        jCheckBox2.setText("Show confirmation");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jCheckBox1.setBackground(jPanel1.getBackground());
        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //FOCUS GAINED MAIL
    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        if(jTextField3.getText().equals("Insert your e-mail..."))
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3FocusGained
    //FOCUS GAINED FIRST NAME
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if(jTextField1.getText().equals("Insert your first name..."))
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained
    //FOCUS GAINED LAST NAME
    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        if(jTextField2.getText().equals("Insert your last name..."))
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained
       //FOCUS LOST FIRST NAME
    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(jTextField1.getText().equals(""))
        jTextField1.setText("Insert your first name...");
    }//GEN-LAST:event_jTextField1FocusLost
    //FOCUS LOST LAST NAME
    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        if(jTextField2.getText().equals(""))
        jTextField2.setText("Insert your last name...");
    }//GEN-LAST:event_jTextField2FocusLost
    //FOCUS LOST MAIL
    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
         if(jTextField3.getText().equals(""))
        jTextField3.setText("Insert your e-mail...");
    }//GEN-LAST:event_jTextField3FocusLost

    //Sign up button action:
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //VERIFY TEXTS
        text txt= new text();
        boolean validFn= txt.check(jTextField1.getText(), jLabel3);
        boolean validLn= txt.check(jTextField2.getText(), jLabel4);
        
        
        //VERIFY MAIL
        mail email= new mail();
        boolean validMail= email.check(jTextField3.getText(), jLabel5);
        
        //VERIFY PWD 
        char[] input = jPasswordField1.getPassword();
        String pass = String.valueOf(input);
        password pwd=new password();
        boolean validPassword= pwd.check(input, jLabel6);
        
        //VERIFY CONFIRMATION
        if(validFn && validLn && validMail && validPassword)
        {   char[] conf = jPasswordField2.getPassword();
            String con = String.valueOf(conf);
            if(con.equals(""))
                { JOptionPane.showMessageDialog(null, "Please confirm your password.\n","Password not confirmed",JOptionPane.WARNING_MESSAGE);
                  jLabel7.setForeground(Color.red);
                }
            else if(!con.equals(pass))
                { JOptionPane.showMessageDialog(null, "Make sure the passwords match!\n","Password confirmation failed",JOptionPane.WARNING_MESSAGE);
                  jLabel7.setForeground(Color.red);
                }
            else
            {
               jLabel7.setForeground(Color.darkGray); 
               AddUser(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),pass);
               setVisible(false);
               Home home=new Home(jTextField3.getText(),pass); 
               //Home.setUpLoading();
               home.setVisible(true);
            }
        }
        
        //ADD USER
         
    }//GEN-LAST:event_jButton1ActionPerformed
    
   //SHOW PASSWORD ACTION
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jPasswordField1.setEchoChar((char)0);
        }
         else
        {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    //SHOW CONFIRMATION ACTION
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
         if(jCheckBox2.isSelected())
        {
            jPasswordField2.setEchoChar((char)0);
        }
         else
        {
            jPasswordField2.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed
   
    //TEST HERE
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
                
                
                
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    //ADD METHOD HERE
    public static void AddUser(String fn,String ln,String mail,String pwd){ 
        try{
            String sql="Insert into user (firstName, lastName, email, password) values(?,?,?,?)";
            pst=conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);
            pst.setString(1,fn);
            pst.setString(2,ln);
            pst.setString(3,mail);
            pst.setString(4,pwd);
            pst.executeUpdate(); 
            rs = pst.getGeneratedKeys();
            rs.next();
            int autoGeneratedID = rs.getInt(1);
            JOptionPane.showMessageDialog(null, "User Successfully Added!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

   
}
