package gestioncv;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.geom.Path2D;
import java.awt.geom.Point2D;
import javax.swing.JFrame;


public class triangle extends javax.swing.JPanel {

    TriangleShape triangleShape;
    Polygon poly;
  
    public triangle() {
        initComponents();
        setBounds(0, 0,10,0);
        
        
        //Top left
        //poly = new Polygon(new int[] { 0, 0, 50 }, new int[] { 0, 50, 0 }, 3);
        //Bottom right
        //poly = new Polygon(new int[] { 50, 50, 0 }, new int[] { 251, 201, 251 }, 3);
        //Top right
        //poly = new Polygon(new int[] { 0, 50, 50 }, new int[] { 0, 50, 0 }, 3);
        //Bottom left
        poly = new Polygon(new int[] { 0, 0, 50 }, new int[] { 251, 201, 251 }, 3);
        repaint();
    }
    
  @Override
  public Dimension getPreferredSize() {
    return new Dimension(100, 251);
  }
  
  @Override
  protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    Graphics2D g2d = (Graphics2D) g.create();
    g2d.translate(0, 0);
    g2d.setColor(Color.RED);
    g2d.fill(poly);
    
    /*g2d.setColor(Color.GREEN);
    g2d.translate(0, 0);
    g2d.fill(triangleShape);
    g2d.dispose();*/

  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


     
    class TriangleShape extends Path2D.Double {
    public TriangleShape(Point2D... points) {
    moveTo(points[0].getX(), points[0].getY());
    lineTo(points[1].getX(), points[1].getY());
    lineTo(points[2].getX(), points[2].getY());
    closePath();
  }
        }
    
    public static void main(String args[]) {
        triangle t= new triangle();
        JFrame p= new JFrame();
        p.add(t);
        p.setVisible(true);
        p.pack();
    }
}

